import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { defineConfig } from 'vite'

const root = dirname(fileURLToPath(import.meta.url))

function elmProgram() {
  return {
    name: 'elm-program',
    transform(_code, id) {
      if (!id.endsWith('.elm')) return null
      const directory = mkdtempSync(join(tmpdir(), 'elm-'))
      const output = join(directory, 'elm.js')
      execFileSync(join(root, 'node_modules', '.bin', 'elm'), ['make', id, '--optimize', `--output=${output}`], {
        cwd: root,
        stdio: 'inherit',
      })
      let compiled = readFileSync(output, 'utf8')
      if (!compiled.includes('(function(scope){')) {
        throw new Error(`Unexpected Elm compiler output for ${id}`)
      }
      compiled = compiled.replace('(function(scope){', 'function __elmInit(scope){')
      const closing = compiled.lastIndexOf('}(this));')
      if (closing < 0) throw new Error(`Could not wrap Elm output for ${id}`)
      compiled = compiled.slice(0, closing) + '}' + compiled.slice(closing + '}(this));'.length)
      return {
        code: `${compiled}
export function start(node, flags) {
  const scope = {}
  __elmInit(scope)
  const program = Object.values(scope.Elm)[0]
  return program.init({ node, flags })
}
`,
        map: null,
      }
    },
  }
}

function inlineBuiltCss() {
  return {
    name: 'inline-built-css',
    apply: 'build',
    closeBundle() {
      const manifest = JSON.parse(readFileSync(join(root, '../static/assets/.vite/manifest.json'), 'utf8'))
      const templates = join(root, '../templates')
      for (const [entry, output] of [['src/islands.js', 'islands-inline.css'], ['src/admin.js', 'admin-inline.css']]) {
        const files = manifest[entry]?.css ?? []
        if (!files.length) throw new Error(`No CSS emitted for ${entry}`)
        let css = files.map(file => readFileSync(join(root, '../static/assets', file), 'utf8')).join('\n')
        if (/\{\{|\{%|\{#/.test(css)) throw new Error(`CSS for ${entry} contains an Askama tag and cannot be inlined`)
        css = css.replace(/<\/style/gi, '<\\/style')
        writeFileSync(join(templates, output), `/* Generated by the frontend build. */\n${css}`)
      }
    },
  }
}

export default defineConfig({
  plugins: [elmProgram(), inlineBuiltCss()],
  base: '/assets/',
  build: {
    outDir: '../static/assets',
    emptyOutDir: true,
    manifest: true,
    assetsDir: '.',
    rollupOptions: {
      input: {
        islands: join(root, 'src/islands.js'),
        admin: join(root, 'src/admin.js'),
      },
    },
  },
  server: {
    port: 5173,
    origin: 'http://localhost:5173',
    proxy: {
      '/api': 'http://localhost:5000',
      '/media': 'http://localhost:5000',
      '/images': 'http://localhost:5000',
    },
  },
})
